package mrs.domain.model;

import java.time.LocalDate;
import java.util.Date;

public class ReservableRoom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservable_room.reserved_date
     *
     * @mbg.generated
     */
    private LocalDate reservedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservable_room.room_id
     *
     * @mbg.generated
     */
    private Integer roomId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservable_room.reserved_date
     *
     * @return the value of reservable_room.reserved_date
     *
     * @mbg.generated
     */
    public LocalDate getReservedDate() {
        return reservedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservable_room.reserved_date
     *
     * @param reservedDate the value for reservable_room.reserved_date
     *
     * @mbg.generated
     */
    public void setReservedDate(LocalDate reservedDate) {
        this.reservedDate = reservedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservable_room.room_id
     *
     * @return the value of reservable_room.room_id
     *
     * @mbg.generated
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservable_room.room_id
     *
     * @param roomId the value for reservable_room.room_id
     *
     * @mbg.generated
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }
}
