version: 0.2

env:
  parameter-store:
    api_url: "/PRODUCTION/API_URL"
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Copy Certfile form S3
      - aws s3 cp s3://mrsorg-mrsnetwork-mrsapplication-cert-bucket/mrsorg-mrsnetwork-mrsapplication.crt ops/ship/codedeploy/nginx/cert.crt
      - aws s3 cp s3://mrsorg-mrsnetwork-mrsapplication-cert-bucket/mrsorg-mrsnetwork-mrsapplication.key ops/ship/codedeploy/nginx/cert.key
  build:
    commands:
      - echo Build started on `date`
      - gradle build -Penv=production -Papi=${api_url}
  post_build:
    commands:
      - echo Build completed on `date`
      - cp build/libs/mrs-0.1.0-SNAPSHOT.jar .
      - cp ops/ship/codedeploy/appspec.yml .
      - cp -r ops/ship/codedeploy/nginx .
      - cp -r ops/ship/codedeploy/scripts .
      - cp -r ops/ship/codedeploy/service .
artifacts:
  files:
    - mrs-0.1.0-SNAPSHOT.jar
    - appspec.yml
    - nginx/**
    - scripts/**
    - service/**
