@startuml
actor 開発者
actor 利用者
cloud "Amazon Web Service" as AWS {
    package "Production Environment" {
      [SpringBoot] as app_prd
    }
    package "Staging Environment" {
      [SpringBoot] as app_stg
    }
}

cloud "Azure" as Azure {
    package "Development Environment" {
      [SpringBoot] as app_dev
    }
}

cloud "GitHub" as github {
  [Git] as repository_1
}

cloud "Azure DevOps" as azuredevops{
  [Git] as repository_2
}
開発者 --> app_dev
開発者 --> app_stg
開発者 --> app_prd
開発者 --> repository_1
開発者 --> repository_2
app_prd <-- 利用者
github <-- AWS
azuredevops <-- Azure
@enduml
