package mrs.infrastructure.datasource;

import mrs.domain.model.room.MeetingRoom;
import mrs.domain.model.room.RoomId;
import org.apache.ibatis.annotations.*;

@Mapper
public interface MeetingRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbg.generated
     */
    @Delete({
            "delete from meeting_room",
            "where room_id = #{value,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(RoomId roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbg.generated
     */
    @Insert({
        "insert into meeting_room (room_id, room_name)",
        "values (#{roomId.value,jdbcType=INTEGER}, #{roomName.value,jdbcType=VARCHAR})"
    })
    int insert(MeetingRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbg.generated
     */
    int insertSelective(MeetingRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "room_id, room_name",
        "from meeting_room",
        "where room_id = #{roomId,jdbcType=INTEGER}"
    })
    @ResultMap("mrs.infrastructure.datasource.MeetingRoomMapper.BaseResultMap")
    MeetingRoom selectByPrimaryKey(Integer roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MeetingRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbg.generated
     */
    @Update({
            "update meeting_room",
            "set room_name = #{roomName.value,jdbcType=VARCHAR}",
            "where room_id = #{roomId.value,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MeetingRoom record);
}
