package mrs.infrastructure.datasource;

import mrs.domain.model.reservation.Reservation;
import org.apache.ibatis.annotations.*;

@Mapper
public interface ReservationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation
     *
     * @mbg.generated
     */
    @Delete({
            "delete from reservation",
            "where reservation_id = #{reservationId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer reservationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation
     *
     * @mbg.generated
     */
    @Insert({
            "insert into reservation (reservation_id, end_time, ",
            "start_time, reserved_date, ",
            "room_id, user_id)",
            "values (#{reservationId.value,jdbcType=INTEGER}, #{reservedTime.end,jdbcType=TIME}, ",
            "#{reservedTime.start,jdbcType=TIME}, #{reservedDate.value,jdbcType=DATE}, ",
            "#{roomId.value,jdbcType=INTEGER}, #{user.userId.value,jdbcType=VARCHAR})"
    })
    int insert(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation
     *
     * @mbg.generated
     */
    int insertSelective(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "reservation_id, end_time, start_time, reserved_date, room_id, user_id",
            "from reservation",
            "where reservation_id = #{reservationId.value,jdbcType=INTEGER}"
    })
    @ResultMap("mrs.infrastructure.datasource.ReservationMapper.BaseResultMap")
    Reservation selectByPrimaryKey(Integer reservationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation
     *
     * @mbg.generated
     */
    @Update({
            "update reservation",
            "set end_time = #{reservedTime.end,jdbcType=TIME},",
            "start_time = #{reservedTime.start,jdbcType=TIME},",
            "reserved_date = #{reservedDate.value,jdbcType=DATE},",
            "room_id = #{roomId.value,jdbcType=INTEGER},",
            "user_id = #{user.userId.value,jdbcType=VARCHAR}",
            "where reservation_id = #{reservationId.value,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Reservation record);
}
