package mrs.infrastructure.datasource;

import mrs.domain.model.todo.Todo;
import org.apache.ibatis.annotations.*;

@Mapper
public interface TodoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated
     */
    @Delete({
            "delete from todo",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated
     */
    @Insert({
            "insert into todo (id, title, ",
            "details, finished)",
            "values (#{id,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
            "#{details,jdbcType=VARCHAR}, #{finished,jdbcType=BIT})"
    })
    int insert(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated
     */
    int insertSelective(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "id, title, details, finished",
            "from todo",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("mrs.infrastructure.datasource.TodoMapper.BaseResultMap")
    Todo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated
     */
    @Update({
            "update todo",
            "set title = #{title,jdbcType=VARCHAR},",
            "details = #{details,jdbcType=VARCHAR},",
            "finished = #{finished,jdbcType=BIT}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Todo record);
}
