package mrs.infrastructure.datasource;

import mrs.domain.model.user.User;
import mrs.domain.model.user.UserId;
import org.apache.ibatis.annotations.*;

@Mapper
public interface UsrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated
     */
    @Delete({
            "delete from usr",
            "where user_id = #{userId.value,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(UserId userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated
     */
    @Insert({
            "insert into usr (user_id, first_name, ",
            "last_name, password, ",
            "role_name)",
            "values (#{userId.value,jdbcType=VARCHAR}, #{name.firstName,jdbcType=VARCHAR}, ",
            "#{name.lastName,jdbcType=VARCHAR}, #{password.value,jdbcType=VARCHAR}, ",
            "#{roleName,jdbcType=VARCHAR})"
    })
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "user_id, first_name, last_name, password, role_name",
            "from usr",
            "where user_id = #{userId.value,jdbcType=VARCHAR}"
    })
    @ResultMap("mrs.infrastructure.datasource.UsrMapper.BaseResultMap")
    User selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated
     */
    @Update({
            "update usr",
            "set first_name = #{name.firstName,jdbcType=VARCHAR},",
            "last_name = #{name.lastName,jdbcType=VARCHAR},",
            "password = #{password.value,jdbcType=VARCHAR},",
            "role_name = #{roleName,jdbcType=VARCHAR}",
            "where user_id = #{userId.value,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(User record);
}
