version: '3'
services:
  web:
    build:
      context: .
      dockerfile: build/docker/amazonlinx2/Dockerfile
    container_name: dev-web
    ports:
      - "20022:20022"
      - "80:80"
      - "8080:8080"
    volumes:
      - ../:/srv/mrs
    privileged: true
    command: /sbin/init
