version: '3'
services:
  web:
    build:
      context: .
      dockerfile: build/docker/AmazonLinux2
    container_name: dev-web
    ports:
      - "20022:20022"
      - "20080:80"
    volumes:
      - ./:/srv/ops
    privileged: true
    command: /sbin/init
