version: '3'
services:
  web:
    build:
      context: .
      dockerfile: build/docker/amazonlinx2/Dockerfile
    container_name: dev-web
    ports:
      - "20022:20022"
      - "20080:80"
    volumes:
      - ../src:/srv/mrs/src
    privileged: true
    command: /sbin/init
